### ISSUE TITLE
GetTickerListAsync prevents retrieving all tickers as stated in the API doc.

### ISSUE THREAD

**Issue by Stereocheck** [binamonk/CoinMarketCapClient#1]
Nice work! Just one quibble....
The API docs for " /ticker/" state:

(int) limit - return a maximum of [limit] results (default is 100, **use 0 to return all results**)

But this line of code in "GetTickerListAsync" prevents the user passing 0 and instead passes no limit value which returns the top 100 only:

uri.Append(limit > 0 ? $"limit={limit}&" : "");

Cheers.

**Comment by binamonk** [comment]
Thank you for the feedback, I will fix it asap.

**Comment by binamonk** [comment]
Issue fixed on merge #4
