### ISSUE TITLE
Project doesn't compile

### ISSUE THREAD

**Issue by sparra1000** [binamonk/CoinMarketCapClient#8]
I tried to rebuild the solution in VS 2017 and get this error:
> Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0535	'CoinMarketCapClientV2' does not implement interface member 'ICoinMarketCapClientV2.GetTickerAsync(int, ConvertEnum)'	CoinMarketCap.DNStandard, CoinMarketCap.PCL 	D:\CoinMarketCapClient-master\CoinMarketCapClient-master\Src\CoinMarketCap.Core\CoinMarketCapClientV2.cs	12	Active

**Comment by binamonk** [comment]
Sorry about that, I in the process of implementing the new API and it pushed to master a wrong version of the code, let me roll back to a working version on master and then you will be able to compile it.

**Comment by sparra1000** [comment]
Ok, I'll check for the roll back and try it again.  Thanks

**Comment by binamonk** [comment]
Ready, master branch now compiles and runs unit tests properly on vs 2017.

**Comment by sparra1000** [comment]
It works, thanks.  Can this ASP.NET Core project be referenced in a non-core ASP.NET web application?

**Comment by binamonk** [comment]
You can use the PCL project to create the library under PCL rules and reference it on your ASP.Net for .Net Framework project.

Also you could reference the CoinMarketCap.Core project as a Shared Library directly on your ASP.Net project.

**Comment by sparra1000** [comment]
Thanks.
